### ISSUE TITLE
make Action buttons have cursor: pointer

### ISSUE THREAD

**Issue by nikolas** [kreezii/jsgam#3]
This makes it more obvious that they are clickable.

In Spooky Adventure, it can be done like this:
```
#MainMenu1-1 {
    cursor: pointer;
}
```

I don't see any template CSS files in the jsgam framework though, so I'm not sure where this belongs.

**Comment by kreezii** [comment]
Spooky Adventure is based on an outdated version of JSGAM. The new engine uses PixiJS.
