### ISSUE TITLE
JSGAM Editor Documentation

### ISSUE THREAD

**Issue by Kev03** [kreezii/jsgam#4]
Hi Kreezii,

do you have any guide/tutorial/documentation available how to use the new JSGAM Editor? 

Thnx for any help :o)

Cheers,

Kevin

**Comment by kreezii** [comment]
I'm working on a complete tutorial to make the adventures and It includes a demo with all the sources. I hope to finish it next week.

**Comment by sabatale** [comment]
@kreezii Wondering if you had a chance to look into it? Keep up the good work!

**Comment by kreezii** [comment]
Documentation is getting updated, slowly but updated in the website.
