### ISSUE TITLE
Missing Tutorial Files

### ISSUE THREAD

**Issue by marceloqla** [kreezii/jsgam#7]
Hello and thanks for your very useful game engine.

I was experimenting with it this weekend but noticed that the tutorial files on : [https://kreezii.github.io/jsgam/firstadventure.html](https://kreezii.github.io/jsgam/firstadventure.html) are all missing.

I managed to download the link below by adding a ".zip" extension like:

> https://kreezii.github.io/jsgam/files/jsgam-tutorial-imgs

TO:

> https://kreezii.github.io/jsgam/files/jsgam-tutorial-imgs.zip

But the character template ".xcf" GIMP file was nowhere to be found

> https://kreezii.github.io/jsgam/files/character-template.xcf

**Comment by kreezii** [comment]
Thank you. All files are now included in one file, fixed links in the tutorial.
